# Generated by Django 4.1.5 on 2023-02-13 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_token_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_expiry',
        ),
    ]
