# Generated by Django 4.1.5 on 2023-02-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_user_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
