# Generated by Django 4.1.5 on 2023-02-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='productid',
            new_name='product',
        ),
    ]
