# Generated by Django 4.1.5 on 2023-03-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
